Feature/cesop pages
wecode-bootcamp-korea/40-1st-Cesop-backend pull request #3
Opened 2022-12-12 08:27 UTC by JeongSooHHH

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
페이지 관련사항

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
전체페이지, 카테고리별 페이지, 특정이름 포함 상품 검색기능 추가
- 상세페이지 구현 필요

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-13 02:33 UTC, kyeongraekim requested changes

2022-12-13 02:33 UTC, kyeongraekim commented on api/models/itemDao.js
> +		 *
제 3자 개발자의 가독성을 위해 asterisk 사용은 지양해주세요! 어떠한 데이터를 끌고 오는지 코드 선에서도 확인할 수 있으면 좋을 것 같습니다.

2022-12-13 02:33 UTC, kyeongraekim commented on api/models/itemDao.js
> +const getItemsByUserId = async id => {
async 뒤에 인자 넣는 곳에 () 소괄호가 보이지 않아보이는데 혹시 해당 함수는 정상작동을 했나요?

2022-12-13 02:33 UTC, kyeongraekim commented on api/routes/itemRouter.js
> +
Resource의 명칭과 파일 명들의 명칭이 서로 일치되어 보지 않습니다. 현재 item이라고 워딩되어 있는 것들을 일괄 product (상품) 계열로 변경해주세요.

2022-12-13 02:33 UTC, kyeongraekim commented on db/migrations/20221206103957_products.sql
> +    FOREIGN KEY (sub_categories) REFERENCES sub_categories (id)
해당 부분은 왜 수정이 이루어지는지 설명해주세요!

2022-12-13 02:33 UTC, kyeongraekim commented on db/migrations/20221206103957_products.sql
> +    price decimal(10),
해당 부분도 왜 수정이 이루어지는지 설명해주세요!

2022-12-13 02:37 UTC, JeongSooHHH commented on db/migrations/20221206103957_products.sql
> +    price decimal(10),
가격이 Won 단위라 소수점은 오히려 가독성을 떨어뜨릴 수 있고 실질적인 의미가 없다는 판단이 들어서 프론트분들과 상의 후 제거하는 쪽으로 의견이 모아졌습니다.

2022-12-13 02:54 UTC, JeongSooHHH commented on db/migrations/20221206103957_products.sql
> +    FOREIGN KEY (sub_categories) REFERENCES sub_categories (id)
해당부분 표기 오류로 
sub_categories -> sub_categories_id
 로 칼럼 변경 및 외래키 재지정하였습니다.

2022-12-13 03:14 UTC, kaeunee commented on api/routes/itemRouter.js
> +
변경하였습니다.

2022-12-13 03:16 UTC, JeongSooHHH commented on api/models/itemDao.js
> +const getItemsByUserId = async id => {
네 정상 작동 했습니다. 
async id  // async name

2022-12-13 03:17 UTC, JeongSooHHH commented on api/routes/itemRouter.js
> +
네 변경하였습니다.

2022-12-14 03:33 UTC, kyeongraekim requested changes

2022-12-14 03:33 UTC, kyeongraekim commented on db/migrations/20221206103957_products.sql
> +    price decimal(10),
어제 말씀 드린 내용처럼 소수점 단위를 자른 후 프론트에게 전달하는 형식으로 고민해보세요!

[다음의 링크를 참고해주세요!](https://codechacha.com/ko/javascript-number-ceil-floor-round/#:~:text=3.-,round()%EB%A5%BC%20%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC%20%EC%86%8C%EC%88%98%EC%A0%90%20n%EC%9E%90%EB%A6%AC%EB%A1%9C%20%EB%B0%98%EC%98%AC%EB%A6%BC,%EB%A5%BC%20%EA%B3%B1%ED%95%98%EA%B3%A0%20%EB%82%98%EB%88%84%EC%8B%9C%EB%A9%B4%20%EB%90%A9%EB%8B%88%EB%8B%A4.)

2022-12-15 09:19 UTC, merged