Feature/cesop cart crud
wecode-bootcamp-korea/40-1st-Cesop-backend pull request #7
Opened 2022-12-14 10:49 UTC by JeongSooHHH

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 중간 구현 목표 - transaction을 적용한 장바구니 CRUD구현

<br />

## :: 구현 사항 설명 - 현재 Cart CRUD 중 Create, Delete 추가하였으며,
Read 부분 "message": "ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'"
에러로 인해 조치중이며, 조치 후 transaction 적용하여 Update 부분 구현 예정입니다.

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
![image](https://user-images.githubusercontent.com/59333783/207575480-2b3d8aab-162d-481c-8f50-3ff5fb410992.png)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-14 12:32 UTC, kyeongraekim requested changes

2022-12-14 12:32 UTC, kyeongraekim commented on api/controllers/cartController.js
> +  //비구조화할당  // 바디라는 개체에서 할당
상용화될 깃헙 코드선에서 불필요한 주석은 꼭 삭제해주셔야 합니다! 코드 독해로 충분히 의미 파악이 가능한 부분임으로 전체 파일에서 일괄적으로 삭제해주세요!~

2022-12-14 12:32 UTC, kyeongraekim commented on api/models/cartDao.js
> +};
cart_item 에서 product_id와 같은 외래키는 사용 기획이 없으실까요? product_name으로 들어오는 상품과, 실제 products 테이블에 존재하는 상품의 데이터가 서로 일치 하지 않는 무결성에 흠이 되는 문제가 생길 수도 있어 보입니다~

2022-12-14 12:32 UTC, kyeongraekim commented on api/models/productDao.js
> +
상세페이지를위해 가은님이 작성하신 getProductById 도 내일중에는 코드내에 녹여주시면 좋을 것 같네요!~

2022-12-14 12:32 UTC, kyeongraekim commented on api/routes/cartRouter.js
> +// router.delete("/:cartId", loginRequired, cartController.deleteFromCart);
해당 주석 내용 확인해주세요!~

2022-12-14 12:33 UTC, kyeongraekim requested changes

2022-12-14 12:33 UTC, kyeongraekim commented on api/models/cartDao.js
> +	   UPDATE cart_items
이곳은 sql update 문이 아직 미완의 상태처럼 보이네요!~

2022-12-14 12:58 UTC, JeongSooHHH commented on api/controllers/cartController.js
> +  //비구조화할당  // 바디라는 개체에서 할당
넵!

2022-12-14 12:59 UTC, JeongSooHHH commented on api/models/cartDao.js
> +};
코드에서 외래키 사용법이 감이 오질 않아 슬랙으로 질문드리겠습니다!

2022-12-14 12:59 UTC, JeongSooHHH commented on api/models/productDao.js
> +
확인해보겠습니다.

2022-12-14 13:00 UTC, JeongSooHHH commented on api/routes/cartRouter.js
> +// router.delete("/:cartId", loginRequired, cartController.deleteFromCart);
네 확인후 처리하겠습니다.

2022-12-16 01:03 UTC, kyeongraekim approved these changes
추후에 실제 써야 하는 코드, 테스트 코드 등의 주석처리 부분은 꼭 삭제한 후 재푸시해주세요!~

2022-12-16 01:03 UTC, merged